Angel Mayo

nombre de feature : pobreza

feature: cpic_rezedu    Carencias promedio de personas en rezago educativo

	2. tipo de problema: Clasificación
    
	3. pregunta: clasifica en las siguientes categorías las carencias de rezago educativo (Severa, Media, Baja)
    
    
    me importan los valores de cpic_rezedu pero se va a apoyar con pobtot_ajustada	Población total

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
 df = pd.read_csv('Indicadores_municipales_sabana_DA.csv', encoding ='latin_1' )
 df.head()

,ent,nom_ent,mun,clave_mun,nom_mun,pobtot_ajustada,pobreza,pobreza_e,pobreza_m,vul_car,...,pobreza_alim_10,pobreza_cap_90,pobreza_cap_00,pobreza_cap_10,pobreza_patrim_90,pobreza_patrim_00,pobreza_patrim_10,gini_90,gini_00,gini_10
0,1,Aguascalientes,1,1001,Aguascalientes,794304,30.531104,2.264478,28.266627,27.983320,...,11.805700,20.4,12.7,18.474600,43.4,33.7,41.900398,0.473,0.425,0.422628
1,1,Aguascalientes,2,1002,Asientos,48592,67.111172,8.040704,59.070468,22.439389,...,21.993299,39.9,29.0,30.980801,64.2,48.9,59.175800,0.379,0.533,0.343879
2,1,Aguascalientes,3,1003,Calvillo,53104,61.360527,7.241238,54.119289,29.428583,...,19.266800,39.5,33.1,28.259199,63.9,57.9,56.504902,0.414,0.465,0.386781
3,1,Aguascalientes,4,1004,Cosío,14101,52.800458,4.769001,48.031458,27.128568,...,14.303200,35.2,21.0,22.386101,59.7,40.1,51.164501,0.392,0.541,0.344984
4,1,Aguascalientes,5,1005,Jesús María,101379,45.338512,6.084037,39.254475,26.262912,...,15.085100,36.6,22.6,22.139999,60.6,42.2,45.703899,0.391,0.469,0.458083

In [3]:
df2 = df[['nom_mun', 'pobtot_ajustada','cpic_rezedu']]
df2

                    nom_mun  pobtot_ajustada  cpic_rezedu
0            Aguascalientes           794304     2.111344
1                  Asientos            48592     2.504305
2                  Calvillo            53104     2.378428
3                     Cosío            14101     2.118768
4               Jesús María           101379     2.221982
...                     ...              ...          ...
2451          Villa Hidalgo            21016     2.655873
2452             Villanueva            27385     2.575823
2453              Zacatecas           117528     2.161391
2454               Trancoso            20456     2.635323
2455  Santa María de la Paz             2772     2.588529

[2456 rows x 3 columns]

In [8]:
bin_edges = [0, 2.51, 4.51, float('inf')]
bin_labels = ['Baja','Media', 'Grave']

df2['class'] = pd.cut(df['cpic_rezedu'], bins=bin_edges, labels=bin_labels)
df2['class'] = df2['class'].astype(str)
print(df2)

                    nom_mun  pobtot_ajustada  cpic_rezedu  class
0            Aguascalientes           794304     2.111344   Baja
1                  Asientos            48592     2.504305   Baja
2                  Calvillo            53104     2.378428   Baja
3                     Cosío            14101     2.118768   Baja
4               Jesús María           101379     2.221982   Baja
...                     ...              ...          ...    ...
2451          Villa Hidalgo            21016     2.655873  Media
2452             Villanueva            27385     2.575823  Media
2453              Zacatecas           117528     2.161391   Baja
2454               Trancoso            20456     2.635323  Media
2455  Santa María de la Paz             2772     2.588529  Media

[2456 rows x 4 columns]

C:\Users\Ivanc\AppData\Local\Temp\ipykernel_2036\3841031879.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['class'] = pd.cut(df['cpic_rezedu'], bins=bin_edges, labels=bin_labels)
C:\Users\Ivanc\AppData\Local\Temp\ipykernel_2036\3841031879.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['class'] = df2['class'].astype(str)

In [9]:
print(df2.columns[3])
pob_rez = df2[['pobtot_ajustada', 'cpic_rezedu']]
classes = df2[['class']]


# print(classes)
# print(pob_rez)
# df2['class'].dtypes
# df2['class'].dtypes

class
      class
0      Baja
1      Baja
2      Baja
3      Baja
4      Baja
...     ...
2451  Media
2452  Media
2453   Baja
2454  Media
2455  Media

[2456 rows x 1 columns]
      pobtot_ajustada  cpic_rezedu
0              794304     2.111344
1               48592     2.504305
2               53104     2.378428
3               14101     2.118768
4              101379     2.221982
...               ...          ...
2451            21016     2.655873
2452            27385     2.575823
2453           117528     2.161391
2454            20456     2.635323
2455             2772     2.588529

[2456 rows x 2 columns]

In [14]:



X_train = pob_rez[:1965]
Y_train = classes[:1965]

X_test = pob_rez[1965:]
Y_test = classes[1965:]
# print(X_train)
# print(X_test)
# print(Y_train)
# print(Y_test)

      pobtot_ajustada  cpic_rezedu
0              794304     2.111344
1               48592     2.504305
2               53104     2.378428
3               14101     2.118768
4              101379     2.221982
...               ...          ...
1960            57179     3.399906
1961           231617     3.529588
1962           101417     3.547899
1963           643551     2.836040
1964           196245     3.769731

[1965 rows x 2 columns]
      pobtot_ajustada  cpic_rezedu
1965           143232     3.236507
1966            25778     3.324229
1967           163384     3.903123
1968            40602     3.175454
1969            90607     2.950650
...               ...          ...
2451            21016     2.655873
2452            27385     2.575823
2453           117528     2.161391
2454            20456     2.635323
2455             2772     2.588529

[491 rows x 2 columns]
      class
0      Baja
1      Baja
2      Baja
3      Baja
4      Baja
...     ...
1960  Media
1961  Media
1962  Media
1963  Media
1964  Media

[1965 rows x 1 columns]
      class
1965  Media
1966  Media
1967  Media
1968  Media
1969  Media
...     ...
2451  Media
2452  Media
2453   Baja
2454  Media
2455  Media

[491 rows x 1 columns]